export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_CART = 'INCRESE_CART';
export const DECREASE_CART = 'DECREASE_CART';
export const RESTAURANT_ITEMS = 'RESTAURANT_ITEMS';
export const EMPTY_CART = 'EMPTY_CART';